# Generated by Django 5.2.7 on 2025-10-30 17:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=80, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'Raça',
                'verbose_name_plural': 'Raças',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'Organização',
                'verbose_name_plural': 'Organizações',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('brinco', models.CharField(max_length=50, verbose_name='brinco/identificador')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1, verbose_name='sexo')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('pelagem', models.CharField(blank=True, max_length=50, verbose_name='pelagem/cor')),
                ('status', models.CharField(choices=[('alive', 'Vivo'), ('sold', 'Vendido'), ('dead', 'Morto'), ('missing', 'Desaparecido')], default='alive', max_length=12, verbose_name='status')),
                ('origem', models.CharField(choices=[('born', 'Nascido na fazenda'), ('purchased', 'Comprado')], default='born', max_length=12, verbose_name='origem')),
                ('data_compra', models.DateField(blank=True, null=True, verbose_name='data da compra')),
                ('preco_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='preço de compra (R$)')),
                ('fornecedor', models.CharField(blank=True, max_length=120, verbose_name='fornecedor')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='animais/', verbose_name='foto')),
                ('mae', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bezerros', to='pastoIO.animal', verbose_name='mãe')),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descendentes', to='pastoIO.animal', verbose_name='pai')),
                ('raca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pastoIO.breed', verbose_name='raça')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastoIO.organization', verbose_name='organização')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'ordering': ['brinco'],
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('cidade', models.CharField(blank=True, max_length=80, verbose_name='cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fazendas/', verbose_name='foto')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastoIO.organization', verbose_name='organização')),
            ],
            options={
                'verbose_name': 'Fazenda',
                'verbose_name_plural': 'Fazendas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='breed',
            name='organizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastoIO.organization', verbose_name='organização'),
        ),
        migrations.CreateModel(
            name='PastureLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('eh_alugado', models.BooleanField(default=False, verbose_name='alugado (gado rendido)')),
                ('alugado_de', models.CharField(blank=True, max_length=120, verbose_name='alugado de')),
                ('aluguel_inicio', models.DateField(blank=True, null=True, verbose_name='início do aluguel')),
                ('aluguel_fim', models.DateField(blank=True, null=True, verbose_name='fim do aluguel')),
                ('aluguel_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='aluguel mensal (R$)')),
                ('capacidade_cabecas', models.PositiveIntegerField(blank=True, null=True, verbose_name='capacidade (cabeças)')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='lotes/', verbose_name='foto')),
                ('fazenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pastoIO.farm', verbose_name='fazenda')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastoIO.organization', verbose_name='organização')),
            ],
            options={
                'verbose_name': 'Lote de pasto',
                'verbose_name_plural': 'Lotes de pasto',
                'ordering': ['nome'],
                'unique_together': {('organizacao', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='AnimalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo_evento', models.CharField(choices=[('birth', 'Nascimento'), ('move', 'Movimentação de lote'), ('vaccine', 'Vacinação'), ('deworm', 'Vermifugação'), ('disease', 'Doença/Tratamento'), ('preg_check', 'Diagnóstico de prenhez'), ('insemination', 'Cobertura/Inseminação'), ('sale', 'Venda'), ('death', 'Morte'), ('weaning', 'Desmama')], max_length=20, verbose_name='tipo de evento')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='data')),
                ('produto', models.CharField(blank=True, max_length=120, verbose_name='produto (vacina/vermífugo/medicamento)')),
                ('dose', models.CharField(blank=True, max_length=60, verbose_name='dose')),
                ('resultado', models.CharField(blank=True, max_length=120, verbose_name='resultado')),
                ('comprador', models.CharField(blank=True, max_length=120, verbose_name='comprador')),
                ('preco_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='preço de venda (R$)')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='pastoIO.animal', verbose_name='animal')),
                ('lote_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='pastoIO.pasturelot', verbose_name='lote de destino')),
                ('lote_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saidas', to='pastoIO.pasturelot', verbose_name='lote de origem')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='lote_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pastoIO.pasturelot', verbose_name='lote atual'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('funcao', models.CharField(blank=True, choices=[('owner', 'Proprietário(a)'), ('cowboy', 'Vaqueiro/Responsável'), ('vet', 'Veterinário(a)')], max_length=20, verbose_name='função')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastoIO.organization', verbose_name='organização')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='dono',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animais_dono', to='pastoIO.person', verbose_name='dono(a)'),
        ),
        migrations.AddField(
            model_name='animal',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animais_responsavel', to='pastoIO.person', verbose_name='responsável'),
        ),
        migrations.CreateModel(
            name='AnimalWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='data')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='peso (kg)')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesagens', to='pastoIO.animal', verbose_name='animal')),
            ],
            options={
                'verbose_name': 'Pesagem',
                'verbose_name_plural': 'Pesagens',
                'ordering': ['-data'],
                'unique_together': {('animal', 'data')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='breed',
            unique_together={('organizacao', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='animal',
            unique_together={('organizacao', 'brinco')},
        ),
    ]
